version: '3.8'
services:
  server:
    image: node:15-alpine
    working_dir: /app
    command: npm run start:dev
    volumes: 
      - ./:/app
    env_file: dev.env
    ports: 
      - 3000:3000
      - 9229:9229